# Generated by Django 5.2.3 on 2025-09-01 03:44

import django.db.models.deletion
import django.utils.timezone
import school_contebras_core_course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCourse', models.CharField(max_length=150, verbose_name='Título do curso')),
                ('description', models.TextField(verbose_name='Descrição do curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Série')),
                ('description', models.TextField(verbose_name='Descrição da Série')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nome de usuário')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Administrador')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da Matéria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Matéria')),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuário')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('surname', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('img', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Foto')),
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo Sanguíneo')),
                ('sex', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Senha (Hash)')),
                ('hire_date', models.DateField(verbose_name='Data de Contratação')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Aviso')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='school_contebras_core_course.classroom', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school_contebras_core_course.course', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Evento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Fim')),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='school_contebras_core_course.classroom', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school_contebras_core_course.grade', verbose_name='Série'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Aula')),
                ('day', models.CharField(choices=[('MONDAY', 'Segunda-feira'), ('TUESDAY', 'Terça-feira'), ('WEDNESDAY', 'Quarta-feira'), ('THURSDAY', 'Quinta-feira'), ('FRIDAY', 'Sexta-feira')], max_length=15, verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Hora de Início')),
                ('end_time', models.TimeField(verbose_name='Hora de Término')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school_contebras_core_course.classroom', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school_contebras_core_course.subject', verbose_name='Matéria')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school_contebras_core_course.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título da Prova')),
                ('date', models.DateField(verbose_name='Data da Prova')),
                ('max_score', models.IntegerField(verbose_name='Pontuação Máxima')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.lesson', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título da Atividade')),
                ('description', models.TextField(verbose_name='Descrição da Atividade')),
                ('due_date', models.DateField(verbose_name='Data de Entrega')),
                ('max_score', models.IntegerField(verbose_name='Pontuação Máxima')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.lesson', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nome de usuário')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('surname', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('img', models.ImageField(blank=True, null=True, upload_to=school_contebras_core_course.models.file_name, verbose_name='Foto')),
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo Sanguíneo')),
                ('sex', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_contebras_core_course.classroom', verbose_name='Turma')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_contebras_core_course.grade', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='RegistrationClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('last_monthly_date', models.DateField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Pontuação')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Correção')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.exam', verbose_name='Prova')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Nota da Prova',
                'verbose_name_plural': 'Notas de Provas',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente')], max_length=10, verbose_name='Status')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.lesson', verbose_name='Aula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Pontuação')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrega')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.assignment', verbose_name='Atividade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Resultado da Atividade',
                'verbose_name_plural': 'Resultados das Atividades',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='grades', to='school_contebras_core_course.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_subjects', to='school_contebras_core_course.teacher', verbose_name='Professores'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_classrooms', to='school_contebras_core_course.teacher', verbose_name='Supervisor'),
        ),
    ]
