# Generated by Django 5.2.3 on 2025-09-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers_for_admin', to='school_contebras_core_course.subject', verbose_name='Matérias'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_subjects', to='school_contebras_core_course.teacher', verbose_name='Professores'),
        ),
    ]
