# Generated by Django 5.2.3 on 2025-08-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do Administrador'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
