# Generated by Django 5.2.3 on 2025-07-16 22:52

import django.db.models.deletion
import django.utils.timezone
import school_contebras_core_course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do Administrador'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password_hash',
            field=models.CharField(max_length=255, verbose_name='Senha (Hash)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='Descrição da Atividade'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.lesson', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título da Atividade'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.assignment', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='score',
            field=models.IntegerField(verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.lesson', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school_contebras_core_course.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school_contebras_core_course.grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_classrooms', to='school_contebras_core_course.teacher', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='titleCourse',
            field=models.CharField(max_length=150, verbose_name='Título do curso'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Data da Prova'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.lesson', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_score',
            field=models.IntegerField(verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título da Prova'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.exam', verbose_name='Prova'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='graded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Correção'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(verbose_name='Descrição da Série'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome da Série'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.classroom', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(verbose_name='Hora de Término'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.subject', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.teacher', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_contebras_core_course.classroom', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='student',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_contebras_core_course.grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=school_contebras_core_course.models.file_name, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome de usuário'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(verbose_name='Descrição da Disciplina'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome da Disciplina'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(verbose_name='Data de Contratação'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do Professor'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password_hash',
            field=models.CharField(max_length=255, verbose_name='Senha (Hash)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='school_contebras_core_course.subject', verbose_name='Disciplinas'),
        ),
    ]
