# Generated by Django 5.2.6 on 2025-10-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='school_contebras_core_course.subject', verbose_name='Matérias'),
        ),
    ]
