# Generated by Django 5.2.3 on 2025-09-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0002_teacher_subjects_alter_subject_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='school_contebras_core_course.teacher', verbose_name='Professores'),
        ),
    ]
