# Generated by Django 5.2.3 on 2025-08-20 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0002_alter_admin_created_at_alter_admin_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='SchoolAdmin',
        ),
    ]
