# Generated by Django 5.2.6 on 2025-10-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0002_course_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='courses_in_classrooms', to='school_contebras_core_course.classroom', verbose_name='Turmas'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_classrooms', to='school_contebras_core_course.course', verbose_name='Curso'),
        ),
    ]
