# Generated by Django 5.2.3 on 2025-08-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0003_grade_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
