# Generated by Django 5.2.6 on 2025-10-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_course', '0003_alter_course_options_course_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level'], 'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.PositiveIntegerField(default=2, help_text='Número identificador da série (ex: 1 = 1º ano, 2 = 2º ano)', unique=True, verbose_name='Nível / Série'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Série'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='grades', to='school_contebras_core_course.subject', verbose_name='Matérias'),
        ),
    ]
