# Generated by Django 5.2.3 on 2025-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_contebras_core_accounts', '0002_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
